# The Docker image that will be used to build your app
image: node:19.5-bullseye-slim
# Functions that should be executed before the build script is run
before_script:
  - npm ci

cache:
  paths:
    - node_modules/

pages:
  # only:
  #   - main
  script:
    - NUXT_APP_BASE_URL=/wiki/$CI_COMMIT_REF_SLUG npm run generate
    - rm -rf public
    - mkdir -p public/$CI_COMMIT_REF_SLUG
    - mv .output/public public/$CI_COMMIT_REF_SLUG
    - ls -l public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
