version: "3.9"
services:
  nuxt:
    build:
      context: .
      target: dev
    container_name: frontend
    volumes:
      - .:/usr/src/app
      - defense-finder-wiki-node-modules:/usr/src/app/node_modules
      - defense-finder-wiki-dotnuxt:/usr/src/app/.nuxt
    ports:
      - "3000:3000"
      - "24678:24678"
      - "4000:4000"
volumes:
  defense-finder-wiki-node-modules:
  defense-finder-wiki-dotnuxt:
